# # roles/example/tasks/main.yml
# - name: added in 2.4, previously you used 'include'
#   import_tasks: redhat.yml
#   when: ansible_facts['os_family']|lower == 'redhat'
# - import_tasks: debian.yml
#   when: ansible_facts['os_family']|lower == 'debian'

# # roles/example/tasks/redhat.yml
# - yum:
#     name: "httpd"
#     state: present

# # roles/example/tasks/debian.yml
# - apt:
#     name: "apache2"
#     state: present

- name: "User creation"
  import_tasks: user.yml

- name: "Provision servers"
  import_tasks: provision.yml
  tags: ['server']

- name: "Selenium service deployment"
  import_tasks: selenium.yml
  tags: ['server']

- name: "Selenium Nessus Scan launcher app deployment"
  import_tasks: deploy.yml
  tags: ['client']
