- name: "Packages update"
  apt:
    update_cache: yes

- name: "Install server APT packages"
  apt:
    pkg:
      - openjdk-8-jre
      - python3

- name: "Install Chrome package"
  apt:
    deb: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'

- name: "Install Chromedriver package"
  unarchive:
    src: 'https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip'
    dest: /opt/selenium/
    remote_src: yes
    owner: selenium
    group: selenium

