- name: 'Create dedicated group'
  group:
    name: selenium
    gid: 1040
  tags:
  - always

- name: 'Create dedicated user'
  user:
    name: selenium
    uid: 1040
    group: selenium
    home: /opt/selenium
  tags:
  - always
